version: '3'
services:

  kibana:
    image: kibana:6.4.2
    ports:
      - "5601:5601"
    networks:
      - app-network  

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "90:80"
      - "444:443"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    volumes:
    - ./mysql:5.7.22/conf:/etc/mysql
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: innodb
      MYSQL_ROOT_PASSWORD: Password@1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

volumes:
  mysql-db:
    driver: local

#Docker Networks
networks:
  app-network:
    driver: bridge